### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by sandyplus** [danlwarren/ENMTools#107]
Hi,
I failed to install the ENMTools package according to your instruction (`install_github("danlwarren/ENMTools")`). I also cannot install from zip file, since I am using a mac (`cannot install Windows binary packages on this platform`).  Would you mind give me some suggestions? Any help would be appreciated.

Best regards,
Sandy

>PS: Error
Downloading GitHub repo danlwarren/ENMTools@master
from URL https://api.github.com/repos/danlwarren/ENMTools/zipball/master
Installing ENMTools
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/vm/m62mf8b90cs0v471dhw_ybmc0000gn/T/RtmpX8o2TD/devtools204d33bc745d/danlwarren-ENMTools-cb86b87'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

>* installing *source* package ‘ENMTools’ ...
** R
** data
*** moving datasets to lazyload DB
** tests
** preparing package for lazy loading
Warning: package ‘raster’ was built under R version 3.4.2
Warning: package ‘sp’ was built under R version 3.4.3
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so
  Reason: image not found
ERROR: lazy loading failed for package ‘ENMTools’
>* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ENMTools’
Installation failed: Command failed (1)

**Comment by danlwarren** [comment]
I've been meaning to make a blog post about this, but for now I'll put it here: a new update to R and/or some packages that ENMTools uses has caused a lot of installation problems.  I just taught a course in Glasgow and we had this exact issue pop up for several people.  I'll copy and paste what Hirzi Luqman, one of the students from the course, did to solve this issue:

For your reference.

Error:
* installing *source* package ‘ENMTools’ ...
** R
** data
*** moving datasets to lazyload DB
** tests
** byte-compile and prepare package for lazy loading
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so':
dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/lib/server/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so
  Reason: image not found
ERROR: lazy loading failed for package ‘ENMTools’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/ENMTools’
Installation failed: Command failed (1)


Problem:
ENMtools/rJava was looking for (and couldn't find) the library "libjvm.dylib" in the directory "/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/lib/server/", because no such directory existed (this refers to a Java 9 installation); I don't know why it looked for the file there...

Solution: I just copied the same file from the Java 8 directory (or whatever Java version is installed on the computer; in my case the directory was "/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/server/") to the R library directory "/Library/Frameworks/R.framework/Versions/3.5/Resources/lib/", and it worked

Please give that a shot and let me know if it does or doesn't work for you.  Cheers!

**Comment by sandyplus** [comment]
Thanks for your quick response.
Finally, I installed ENMTools by this command: `sudo ln -f -s $(/usr/libexec/java_home)/jre/lib/server/libjvm.dylib /usr/local/lib`. 
I found this from [HERE](https://stackoverflow.com/questions/30738974/rjava-load-error-in-rstudio-r-after-upgrading-to-osx-yosemite)

**Comment by tufui57** [comment]
Dear Dr. Warren,
I failed to install the ENMTools package using
install_github("danlwarren/ENMTools") 
and 
install_local("C:\\Users\\User name\\Downloads\\ENMTools-master.zip")).
Both gave me the same error;

Error in read.dcf(path) : 
  Found continuation line starting '	person("Olivier", " ...' at begin of record.

Could you give me tips to solve this?

Sincerely,
Miki

**Comment by danlwarren** [comment]
I believe that's an issue with ecospat.  Could you try installing it manually and then install ENMTools?

**Comment by tufui57** [comment]
Thanks. I could install ENMTools after manually updating several packages in addition to ecospat.
