### ISSUE TITLE
raster.cor vs raster.cor.matrix

### ISSUE THREAD

**Issue by nahuron** [danlwarren/ENMTools#119]
default method on raster.cor is "spearman" whereas default on raster.cor.matrix is "pearson". Not sure if this is intentional, but it might be better to set them to be the same default?

**Comment by danlwarren** [comment]
That was actually intentional; for the most part that function is used for measuring similarity between ENMs, for which I think Spearman is more relevant.  Pearson makes more sense (and is more commonly used) for climate variables, though, and that's what those raster.cor.matrix and raster.cor.plot functions are typically used for.  It could always be changed so that the default is Pearson and the overlap functions specify Spearman when they call it, but IMO that's just as confusing but in the opposite direction.

**Comment by danlwarren** [comment]
Yeah actually I think it's something I should do a blog post about...eventually.

**Comment by nahuron** [comment]
Haha, yeah I could see that being beneficial. For the most part, folks that are just getting their feet wet with ENMs stick to the recipe that they see in the methods section of papers (I am definitely guilty of this at times).

Nicholas A. Huron
Graduate Student in Biology, Temple University
B.S. Biology, Pepperdine University
nicholashuron.com <http://nicholashuron.strikingly.com/>
