### ISSUE TITLE
Predict function for projecting to other times/places

### ISSUE THREAD

**Issue by danlwarren** [danlwarren/ENMTools#84]
We need something we can pass enmtools.model objects to to make projections to other times/places.  Would be nice to wrap those prediction objects up with some sort of other plots comparing environment spaces, etc.

**Comment by danlwarren** [comment]
Note: this can take the form of good ol' S3 functions since we've got classes defined for enmtools model objects (e.g., predict.enmtools.glm, predict.enmtools.gam, etc).

**Comment by danlwarren** [comment]
The comparison plots can be made now using threespace.plot.

**Comment by danlwarren** [comment]
Okay, this is now implemented.

**Comment by leonardslog** [comment]
Hello Dan, 

Is there an easy or even roundabout way to project an enmtools.model object onto the totality of an environmental dataset (rather than the 2 dimensional solution of 'visualize.enm')? Essentially thinking about back or forward projecting a model generated from env current data onto the same geographic extent but with different environmental variables (e.g. paleoclim) using the . Thanks in advance and apologies if this has already been addressed or intuitive in the existing code!

**Comment by danlwarren** [comment]
That should just be possible with the "predict" function, unless I'm misunderstanding you.  You can just do 

my.future <- predict(model.object, future.env)

That will give you a suitability raster, a clamping raster, and a plot of the relationship between the training data and the layers you're predicting onto.
